<?php 
/* Template Name: Test PDF */
require_once get_template_directory() . '/dompdf/autoload.inc.php';
use Dompdf\Dompdf;
if (1) {
	$postType 	=  '';
	$filename = "Test Summary";
	$dompdf = new Dompdf();
    $company    = advisory_get_user_company();
    $dependencies = advisory_get_dashboard_report_card_data();
    $data = advisory_prepare_export_data($dependencies);
	if (!empty($data)) {
		$html = '';
		$html .= '<style>';
            $html .= '@page {margin: 10px 10px 20px 10px; }';
            $html .= '*{font-family: sans-serif;line-height:1.1;font-size: 12px;}';
            $html .= 'table {border-collapse: collapse;}';
            $html .= 'table td, table th{vertical-align: middle;}';
            $html .= '.m-0{margin:0;}';
            $html .= '.clearfix{clear: both;}';
            // HEADER
            $html .= '.header{}';
            $html .= '.titleContainer{float: left;}';
            $html .= '.title{ font-size: 22px; margin: 0;}';
            $html .= '.reportDate{margin: 0;font-weight:bold; padding-top: 7px;}';
            $html .= '.companyContainer{ text-align:center; padding-right: 20%;}';
            $html .= '.companyName{font-size: 17px;font-weight: 700; margin:0;}';
            // LEGEND
            $html .= '.legendContainer{margin: 30px 0 0 900px; }';
            $html .= '.legends{margin: 0;padding: 0;}';
            $html .= '.legends li{ list-style: none; font-weight: 600; /*font-size: 14px;*/}';
            // CONTENT
            $html .= '.contentTitle{ font-size:14px; font-weight: 700;margin: 0 0 10px 0;}';
            $html .= '.content{border-top: 2px solid #000000; width: 100%;}';
            $html .= '.content thead{}';
            $html .= '.content thead tr{ text-align:left !important;}';
            $html .= '.content thead tr th{border-bottom: 1px solid #000000;padding: 10px 0 5px 0;}';
            $html .= '.content tbody{}';
            $html .= '.content tbody tr td{padding: 2px 0;}';
            $html .= '.content tbody tr:nth-child(even) td{background:#e2e2e2;}';
            // $html .= '.content tbody tr:nth-child(even) td{background:#f9f9f9;}';
        $html .= '</style>';
        // HEADER
        $html .= '<div class="header">';
            $html .= '<div class="titleContainer">';
                $html .= '<h1 class="title">IT service Catalogue</h1>';
                $html .= '<p class="reportDate">Report Date: August 18th, 2020</p>';
            $html .= '</div>';
            $html .= '<div class="companyContainer">';
                $html .= '<p class="companyName">'.$company->name.'</p>';
            $html .= '</div>';
            $html .= '<div class="clearfix"></div>';
        $html .= '</div>';
        // LEGEND
        $html .= '<div class="legendContainer">';
            $html .= '<ul class="legends">';
                $html .= '<li>RTO - Recovery Time Objective</li>';
                $html .= '<li>RPO - Recovery Point Objective</li>';
                $html .= '<li>CL - Criticality Level</li>';
            $html .= '</ul>';
        $html .= '</div>';
        // CONTENT
        $html .= '<h2 class="contentTitle">Service: Application Services</h2>';
        $html .= '<table class="content">';
            $html .= '<thead>';
                $html .= '<tr>';
                    $html .= '<th>####</th>';
                    $html .= '<th>Technology Dependency</th>';
                    $html .= '<th>Department</th>';
                    $html .= '<th>Service/Process</th>';
                    $html .= '<th>RTO</th>';
                    $html .= '<th>RPO</th>';
                    $html .= '<th>CL</th>';
                    $html .= '<th>Tier</th>';
                $html .= '</tr>';
            $html .= '</thead>';
            $html .= '<tbody>';
                foreach ($data as $item_si => $item) {
                    if ($item_si > 5) break;
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td>'.($item_si + 1).'</td>';
                        $html .= '<td>'.$item['Technology Dependency'].'</td>';
                        $html .= '<td>'.$item['Department'].'</td>';
                        $html .= '<td>'.$item['Service/Process'].'</td>';
                        $html .= '<td>'.$item['RTO'].'</td>';
                        $html .= '<td>'.$item['RPO'].'</td>';
                        $html .= '<td>'.$item['CL'].'</td>';
                        $html .= '<td>'.$item['Tier'].'</td>';
                    $html .= '</tr>';
                }
            $html .= '</tbody>';
        $html .= '</table>';
    
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->set_option("isPhpEnabled", true);
        $dompdf->render();
        $dompdf->get_canvas()->page_text(788, 578, "Page : {PAGE_NUM} of {PAGE_COUNT}", '', 8, array(0,0,0));
	}
	$dompdf->stream($filename,array("Attachment"=>0));
}
?>