<?php 
/* Template Name: Test PDF */
require_once get_template_directory() . '/dompdf/autoload.inc.php';
use Dompdf\Dompdf;
if (0) {
	$postType 	=  '';
	$filename = "Test Summary";
	$dompdf = new Dompdf();
	if ( 1 ) {
		$html = '';
		$html = '<style>';
            $html .= '@page {margin: 50px 48px; }';
            $html .= '*{font-family: sans-serif;line-height:1.1;font-size: 13px;}';
            $html .= 'input, textarea{border:none;background:#F1F4FF;width:100%;}';
            $html .= 'input{padding:5px 0;}';
            $html .= 'textarea{resize:none;}';
            $html .= 'input:focus, input:active, textarea:focus, textarea:active{border:none;outline:none;background:transparent;}';
            $html .= 'table {border-collapse: collapse;}';
            $html .= 'table td, table th{vertical-align: middle;}';
            $html .= 'table td.padding, table th.padding{padding:5px;}';
            $html .= '.m-0{margin:0;}';
            $html .= '.m-5{margin:5px 0;}';
            $html .= '.clearfix{clear: both;}';
            $html .= '.bordered{border:1px solid #000;}';
            $html .= '.smallfont{font-size:12px;}';
            $html .= '.half{width:50%;}';
            $html .= '.bb{border-bottom:1px solid !important}';
            $html .= '.transparentbg{background:transparent !important;}';
            $html .= '.inputbg{background:#F1F4FF !important; font-size:14px;padding:2px 3px;}';
            // HEADER
            $html .= '.header{text-align:center;font-size:12px;letter-spacing:0.1px;}';
            $html .= '.title{font-weight: bold; font-size: 16px;margin: 13px 0 8px 0;}';
            $html .= '.container{width:622px;margin:0 auto;}';
            $html .= '.container > div{padding:8px 6px;}';
            $html .= '.container table{width:100%;}';
            $html .= '.heading_1{font-size:16px; background:#000; color: #ffffff;}';
            $html .= '.heading_2{font-size:16px; background:#1F3864; color: #ffffff;}';
            $html .= '.description{background:#D9E2F3;border-bottom:1px solid #000;}';
            $html .= '.description ul{padding:0 0 0 16px;margin:0;}';
            $html .= '.teamactivities thead td{padding:8px 6px;font-size:13px;background:#D9D9D9;font-weight:normal;}';
            $html .= '.signature thead td{padding:8px 6px;font-size:13px;background:#1F3864;text-align:center;color:#ffffff;}';
            $html .= '.signature td.border{border-bottom: 1px solid #000;}';
            // PAGE 2
            $html .= '.heading_2_2 {font-size: 16px; background: #7030A0; color: #ffffff; }';
            $html .= '.description_2_1{background: #E8E1EB; border-bottom: 1px solid #000; }';
            $html .= '.description_2_1 p{margin: 0;}';
            $html .= '.description_2_2{background: #D9D9D9; border-top: 1px solid #000; border-bottom: 1px solid #000; }';
            $html .= '.description_2_2 p{margin: 0;}';
            $html .= '.form_2_1 table{margin-bottom: 2px;}';
            $html .= '.form_2_2 table{margin-bottom: 15px;}';
            $html .= '.form_2_2 table.p_2_small_table {width: 410px}';
            $html .= '.form_2_2 .signature input{margin-bottom: 15px;}';
            $html .= '.comments_2 i{font-size: 12px; line-height: 1.5; }';
            $html .= '.heading-bottom{text-align: center; background: #000; color:#ffffff; padding-top: 5px;}';
            $html .= '.description_2_3 {text-align: center; padding: 0 10px; }';
            $html .= '.container table.signoff {width: 91%; margin: 0 auto 10px auto; }';
            $html .= '.container table.signoff thead td{text-align: center; background: #7030A0; padding: 8px 6px; color: #fff;font-size: 12px}';
            $html .= '.container table.signoff tbody td input {margin-top: 9px; border-bottom: 2px solid; }';
            $html .= '.container table.signoff_2 tbody td input {margin-top: 15px;}';
            
            // $html .= 'body {width:800px;margin:0 auto;}';
        $html .= '</style>';
        
        $html .= '<div class="header">Town of Whitby – Disaster Management Forms: Event Recording</div>';
        $html .= '<div class="title">Event Recording Form</div>';
        $html .= '<div class="container bordered">';
            $html .= '<div class="heading_1">Step 1</div>';
            $html .= '<div class="heading_2">Disaster Recovery Event Recording Form</div>';
            $html .= '<div class="description">';
                $html .= '<ul>';
                    $html .= '<li>All key events from a major disruption in TIS services must be recorded.</li>';
                    $html .= '<li>All event logs shall be maintained by the disaster recovery team leader.</li>';
                    $html .= '<li>This event log shall be started at the commencement of an incident by the incident response team/disaster recovery team and passed to the business recovery team once the initial disruption has been controlled.</li>';
                    $html .= '<li>The following event log should be completed by the disaster recovery team leader to record all key events during disaster recovery, until such a time as responsibility is handed over to the business recovery team</li>';
                $html .= '</ul>';
            $html .= '</div>';
            $html .= '<div class="form">';
                $html .= '<p class="m-0">Description of Disruption/Disaster:</p>';
                $html .= '<p class="m-5 inputbg">The following event log should be completed by the disaster recovery team leader to record all key events during disaster recovery, until such a time as responsibility is handed over to the business recovery team</p>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td width="100">Commencement Date:</td>';
                        $html .= '<td class="inputbg">12/12/2020</td>';
                        $html .= '<td width="140">Date/Time DR Team Mobilized:</td>';
                        $html .= '<td class="inputbg">12/12/2020</td>';
                    $html .= '</tr>';
                $html .= '</table>';
            $html .= '</div>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container">';
            $html .= '<table border="1" class="teamactivities">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td style="width:120px">DR Team Activities</td>';
                        $html .= '<td style="width:80px">Date/Time</td>';
                        $html .= '<td>Outcome</td>';
                        $html .= '<td style="width:160px">Follow-up Action Required</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td class="inputbg">Lorem ipsum<br>Lorem ipsum<br>Lorem ipsum</td>';
                        $html .= '<td class="inputbg">dolor</td>';
                        $html .= '<td class="inputbg">amet consectetur adipisicing <br>amet consectetur adipisicing</td>';
                        $html .= '<td class="inputbg">Alias, minima.</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="inputbg">Lorem ipsum<br>Lorem ipsum<br>Lorem ipsum</td>';
                        $html .= '<td class="inputbg">dolor</td>';
                        $html .= '<td class="inputbg">amet consectetur adipisicing <br>amet consectetur adipisicing</td>';
                        $html .= '<td class="inputbg">Alias, minima.</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="inputbg">Lorem ipsum<br>Lorem ipsum<br>Lorem ipsum</td>';
                        $html .= '<td class="inputbg">dolor</td>';
                        $html .= '<td class="inputbg">amet consectetur adipisicing <br>amet consectetur adipisicing</td>';
                        $html .= '<td class="inputbg">Alias, minima.</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="inputbg">Lorem ipsum<br>Lorem ipsum<br>Lorem ipsum</td>';
                        $html .= '<td class="inputbg">dolor</td>';
                        $html .= '<td class="inputbg">amet consectetur adipisicing <br>amet consectetur adipisicing</td>';
                        $html .= '<td class="inputbg">Alias, minima.</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="inputbg">Lorem ipsum<br>Lorem ipsum<br>Lorem ipsum</td>';
                        $html .= '<td class="inputbg">dolor</td>';
                        $html .= '<td class="inputbg">amet consectetur adipisicing <br>amet consectetur adipisicing</td>';
                        $html .= '<td class="inputbg">Alias, minima.</td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container bordered">';
            $html .= '<table style="margin: 5px 0;">';
                $html .= '<tr>';
                    $html .= '<td style="text-align:right;width:50%">Disaster Recovery Team’s Work Completed: &nbsp;</td>';
                    $html .= '<td class="inputbg">Lorem ipsum dolor sit emit</td>';
                $html .= '</tr>';
                $html .= '<tr>';
                    $html .= '<td style="text-align:right;width:50%">Event Log Passed to Business Recovery Team: &nbsp;</td>';
                    $html .= '<td class="inputbg">Lorem ipsum dolor sit emit</td>';
                $html .= '</tr>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container">';
            $html .= '<table class="signature">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td>Disaster Recovery Team Leader:</td>';
                        $html .= '<td style="width:50px;">&nbsp;</td>';
                        $html .= '<td style="width:220px;">Sign-off:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td>&nbsp;</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="bb inputbg">Lorem ipsum dolor sit emit</td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td class="border">Lorem ipsum dolor si</td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';
        // PAGE 2
        $html .= '<div class="header" style="page-break-before: always; position: relative;">Town of Whitby – Disaster Management Forms: Event Recording</div>';
        $html .= '<div class="title">Business Resumption</div>';
        $html .= '<div class="container bordered">';
            $html .= '<div class="heading_1">Step 2</div>';
            $html .= '<div class="heading_2_2">Business Resumption Form – Application Recovery</div>';
            $html .= '<div class="description_2_1">';
                $html .= '<p style="margin-bottom: 7px">The following transition form should be completed and signed by the business recovery team leader and the responsible business unit leader, for each application recovered at time of disruption/disaster and time of failback to normal operations.</p>';
                $html .= '<p>';
                   $html .= 'A separate form is recommended for each department that has 1 or more business service/process(es) that requires the application to function.';
                $html .= '</p>';
            $html .= '</div>';
            $html .= '<div class="form_2_1">';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 120px;">Name of Application:</td>';
                        $html .= '<td class="inputbg">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, minima.</td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 207px;">Business Service/Process <br> <i>(include all key services/processes)</i> </td>';
                        $html .= '<td class="inputbg">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias, minima.elit. Alias, minima.</td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 415px;">Completion Date of the Work Provided by the Business Recovery Team</td>';
                        $html .= '<td class="inputbg">elit. Alias, minima.</td>';
                    $html .= '</tr>';
                $html .= '</table>';
            $html .= '</div>';
            $html .= '<div class="description_2_2">';
                $html .= '<p>I confirm that the work of the business recovery team has been completed in accordance with the disaster recovery plan for the above application, and that normal business operations have been effectively restored at a level in accordance with the disaster recovery invocation guide and supporting documentation.</p>';
            $html .= '</div>';
            $html .= '<div class="form_2_2">';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 223px;;">Business Recovery Team Lead Name:</td>';
                        $html .= '<td class="inputbg">Lorem ipsum dolor sit, amet consectetur adipisicing elit.</td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table class="p_2_small_table signature_2">';
                    $html .= '<tr>';
                        $html .= '<td style="width: 75px;">Signature:</td>';
                        $html .= '<td class="bb transparentbg">restored at a level in accordance</td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table class="p_2_small_table date">';
                    $html .= '<tr>';
                        $html .= '<td style="width: 33px;">Date:</td>';
                        $html .= '<td class="bb inputbg">10/12/2020</td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<div class="comments_2">';
                    $html .= '<i>(Any comments by the BRT leader in connection with the return of this business process should be made here.)</i>';
                    $html .= '<p class="m-0 inputbg">I confirm that the above application is now acceptable to working conditions to support the business service/process in accordance with the disaster recovery invocation guide and supporting documentation.</p>';
                $html .= '</div>';
            $html .= '</div>';
            $html .= '<div class="heading-bottom"> DEPARTMENTAL LEAD SIGNOFF </div>';
            $html .= '<p class="description_2_3"> I confirm that the above application is now acceptable to working conditions to support the business service/process in accordance with the disaster recovery invocation guide and supporting documentation. </p>';
            $html .= '<table class="signoff">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td width="170">Name:</td>';
                        $html .= '<td width="10" style="background: transparent;">&nbsp;</td>';
                        $html .= '<td>Title:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr><td colspan="3" style="font-size:8px;">&nbsp;</td></tr>';
                    $html .= '<tr>';
                        $html .= '<td class="bb inputbg">guide and supporting documentation.</td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td class="bb inputbg">recovery invocation</td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
            $html .= '<table class="signoff signoff_2">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td>Signature:</td>';
                        $html .= '<td width="25" style="background: transparent;">&nbsp;</td>';
                        $html .= '<td width="150">Date:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr><td colspan="3" style="font-size:10px;">&nbsp;</td></tr>';
                    $html .= '<tr>';
                        $html .= '<td class="bb transparentbg">recovery invocation</td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td class="bb inputbg">12/12/2020</td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';

        $bottomLine = '_________________________________________________________________________________________________________';
    
        $dompdf->loadHtml($html);
        // $dompdf->setPaper('A4', 'landscape');
        $dompdf->set_option("isPhpEnabled", true);
        $dompdf->render();
        $dompdf->get_canvas()->page_text(72, 740, $bottomLine, '', 8, array(0,0,0));
        // $dompdf->get_canvas()->page_text(174, 38, "Town of Whitby – Disaster Management Forms: Event Recording", '', 9, array(0,0,0));
        $dompdf->get_canvas()->page_text(530, 760, "{PAGE_NUM} | Page", '', 10, array(0,0,0));
	}
	$dompdf->stream($filename,array("Attachment"=>0));
} else {
        $html = '<style>';
            $html .= '@page {margin: 50px 48px; }';
            $html .= '*{font-family: sans-serif;line-height:1.1;font-size: 13px;}';
            $html .= 'input, textarea{border:none;background:#F1F4FF;width:100%;}';
            $html .= 'input{padding:5px 0;}';
            $html .= 'textarea{resize:none;}';
            $html .= 'input:focus, input:active, textarea:focus, textarea:active{border:none;outline:none;background:transparent;}';
            $html .= 'table {border-collapse: collapse;}';
            $html .= 'table td, table th{vertical-align: middle;}';
            $html .= 'table td.padding, table th.padding{padding:5px;}';
            $html .= '.m-0{margin:0;}';
            $html .= '.m-5{margin:5px 0;}';
            $html .= '.clearfix{clear: both;}';
            $html .= '.bordered{border:1px solid #000;}';
            $html .= '.smallfont{font-size:12px;}';
            $html .= '.half{width:50%;}';
            // HEADER
            $html .= '.header{text-align:center;font-size:12px;letter-spacing:0.1px;}';
            $html .= '.title{font-weight: bold; font-size: 16px;margin: 13px 0 8px 0;}';
            $html .= '.container{width:622px;margin:0 auto;}';
            $html .= '.container > div{padding:8px 6px;}';
            $html .= '.container table{width:100%;}';
            $html .= '.heading_1{font-size:16px; background:#000; color: #ffffff;}';
            $html .= '.heading_2{font-size:16px; background:#1F3864; color: #ffffff;}';
            $html .= '.description{background:#D9E2F3;border-bottom:1px solid #000;}';
            $html .= '.description ul{padding:0 0 0 16px;margin:0;}';
            $html .= '.teamactivities thead td{padding:8px 6px;font-size:13px;background:#D9D9D9;font-weight:normal;}';
            $html .= '.signature thead td{padding:8px 6px;font-size:13px;background:#1F3864;text-align:center;color:#ffffff;}';
            $html .= '.signature td.border{border-bottom: 1px solid #000;}';
            // PAGE 2
            $html .= '.heading_2_2 {font-size: 16px; background: #7030A0; color: #ffffff; }';
            $html .= '.description_2_1{background: #E8E1EB; border-bottom: 1px solid #000; }';
            $html .= '.description_2_1 p{margin: 0;}';
            $html .= '.description_2_2{background: #D9D9D9; border-top: 1px solid #000; border-bottom: 1px solid #000; }';
            $html .= '.description_2_2 p{margin: 0;}';
            $html .= '.form_2_2 table{margin-bottom: 15px;}';
            $html .= '.form_2_2 table.p_2_small_table {width: 410px}';
            $html .= '.form_2_2 .signature input{margin-bottom: 15px;}';
            $html .= '.comments_2 i{font-size: 12px; line-height: 1.5; }';
            $html .= '.heading-bottom{text-align: center; background: #000; color:#ffffff; padding-top: 5px;}';
            $html .= '.description_2_3 {text-align: center; padding: 0 10px; }';
            $html .= '.container table.signoff {width: 91%; margin: 0 auto 10px auto; }';
            $html .= '.container table.signoff thead td{text-align: center; background: #7030A0; padding: 8px 6px; color: #fff;font-size: 12px}';
            $html .= '.container table.signoff tbody td input {margin-top: 9px; border-bottom: 2px solid; }';
            $html .= '.container table.signoff_2 tbody td input {margin-top: 15px;}';

            $html .= 'body {width:710px;margin:0 auto;}';
        $html .= '</style>';
        
        $html .= '<div class="clearfix"><br><br><br><br></div>';
        $html .= '<div class="header">Town of Whitby – Disaster Management Forms: Event Recording</div>';
        $html .= '<div class="title">Event Recording Form</div>';
        $html .= '<div class="container bordered">';
            $html .= '<div class="heading_1">Step 1</div>';
            $html .= '<div class="heading_2">Disaster Recovery Event Recording Form</div>';
            $html .= '<div class="description">';
                $html .= '<ul>';
                    $html .= '<li>All key events from a major disruption in TIS services must be recorded.</li>';
                    $html .= '<li>All event logs shall be maintained by the disaster recovery team leader.</li>';
                    $html .= '<li>This event log shall be started at the commencement of an incident by the incident response team/disaster recovery team and passed to the business recovery team once the initial disruption has been controlled.</li>';
                    $html .= '<li>The following event log should be completed by the disaster recovery team leader to record all key events during disaster recovery, until such a time as responsibility is handed over to the business recovery team</li>';
                $html .= '</ul>';
            $html .= '</div>';
            $html .= '<div class="form">';
                $html .= '<p class="m-0">Description of Disruption/Disaster:</p>';
                $html .= '<textarea name="" cols="30" rows="5"></textarea>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width:132px">Commencement Date:</td>';
                        $html .= '<td><input type="text"></td>';
                        $html .= '<td style="width:180px">Date/Time DR Team Mobilized:</td>';
                        $html .= '<td><input type="text" style=""></td>';
                    $html .= '</tr>';
                $html .= '</table>';
            $html .= '</div>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container">';
            $html .= '<table border="1" class="teamactivities">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td style="width:120px">DR Team Activities</td>';
                        $html .= '<td style="width:80px">Date/Time</td>';
                        $html .= '<td>Outcome</td>';
                        $html .= '<td style="width:160px">Follow-up Action Required</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                        $html .= '<td><textarea name="" style="width: 100%" cols="10" rows="3"></textarea></td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container bordered">';
            $html .= '<table style="margin: 5px 0;">';
                $html .= '<tr>';
                    $html .= '<td style="text-align:right;width:50%">Disaster Recovery Team’s Work Completed:</td>';
                    $html .= '<td><input type="text"></td>';
                $html .= '</tr>';
                $html .= '<tr>';
                    $html .= '<td style="text-align:right;width:50%">Event Log Passed to Business Recovery Team:</td>';
                    $html .= '<td><input type="text"></td>';
                $html .= '</tr>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br>';
        $html .= '<div class="container">';
            $html .= '<table class="signature">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td>Disaster Recovery Team Leader:</td>';
                        $html .= '<td style="width:50px;">&nbsp;</td>';
                        $html .= '<td style="width:220px;">Sign-off:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td>&nbsp;</td>';
                    $html .= '</tr>';
                    $html .= '<tr>';
                        $html .= '<td class="border"><input type="text"></td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td class="border"><input type="text" style="background: transparent;"></td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br><br><br><br>';

        // PAGE 2
        $html .= '<div class="header">Town of Whitby – Disaster Management Forms: Event Recording</div>';
        $html .= '<div class="title">Business Resumption</div>';
        $html .= '<div class="container bordered">';
            $html .= '<div class="heading_1">Step 2</div>';
            $html .= '<div class="heading_2_2">Business Resumption Form – Application Recovery</div>';
            $html .= '<div class="description_2_1">';
                $html .= '<p style="margin-bottom: 7px">The following transition form should be completed and signed by the business recovery team leader and the responsible .business unit leader, for each application recovered at time of disruption/disaster and time of failback to normal operations.</p>';
                $html .= '<p>A separate form is recommended for each department that has 1 or more business service/process(es) that requires the application to function..</p>';
            $html .= '</div>';
            $html .= '<div class="form_2_1">';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 118px;">Name of Application</td>';
                        $html .= '<td><input type="text" /></td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 207px;">Business Service/Process <br> <i>(include all key services/processes)</i> </td>';
                        $html .= '<td><textarea name="" cols="33" rows="4"></textarea></td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 415px;">Completion Date of the Work Provided by the Business Recovery Team</td>';
                        $html .= '<td><input type="text" style="" /></td>';
                    $html .= '</tr>';
                $html .= '</table>';
            $html .= '</div>';
            $html .= '<div class="description_2_2">';
                $html .= '<p>I confirm that the work of the business recovery team has been completed in accordance with the disaster recovery plan for the above application, and that normal business operations have been effectively restored at a level in accordance with the disaster recovery invocation guide .and supporting documentation.</p>';
            $html .= '</div>';
            $html .= '<div class="form_2_2">';
                $html .= '<table>';
                    $html .= '<tr>';
                        $html .= '<td style="width: 223px;;">Business Recovery Team Lead Name:</td>';
                        $html .= '<td><input type="text" /></td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table class="p_2_small_table signature_2">';
                    $html .= '<tr>';
                        $html .= '<td style="width: 75px;">Signature:</td>';
                        $html .= '<td><input style="width: 100%;border-bottom: 2px solid #000;background: transparent;" type="text"></td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<table class="p_2_small_table date">';
                    $html .= '<tr>';
                        $html .= '<td style="width: 33px;">Date:</td>';
                        $html .= '<td><input type="text" style="" /></td>';
                    $html .= '</tr>';
                $html .= '</table>';
                $html .= '<div class="comments_2">';
                    $html .= '<i>(Any comments by the BRT leader in connection with the return of this business process should be made here.)</i>';
                    $html .= '<textarea name="" cols="30" rows="5"></textarea>';
                $html .= '</div>';
            $html .= '</div>';
            $html .= '<div class="heading-bottom"> DEPARTMENTAL LEAD SIGNOFF </div>';
            $html .= '<p class="description_2_3"> I confirm that the above application is now acceptable to working conditions to support the business service/process in .accordance with the disaster recovery invocation guide and supporting documentation. </p>';
            $html .= '<table class="signoff">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td width="220">Name:</td>';
                        $html .= '<td style="background: transparent;">&nbsp;</td>';
                        $html .= '<td>Title:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td><input type="text"></td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td><input type="text"></td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
            $html .= '<table class="signoff signoff_2">';
                $html .= '<thead>';
                    $html .= '<tr>';
                        $html .= '<td>Signature:</td>';
                        $html .= '<td width="32" style="background: transparent;">&nbsp;</td>';
                        $html .= '<td width="200">Date:</td>';
                    $html .= '</tr>';
                $html .= '</thead>';
                $html .= '<tbody>';
                    $html .= '<tr>';
                        $html .= '<td><input type="text" style="background: transparent;"></td>';
                        $html .= '<td>&nbsp;</td>';
                        $html .= '<td><input type="text"></td>';
                    $html .= '</tr>';
                $html .= '</tbody>';
            $html .= '</table>';
        $html .= '</div>';
        $html .= '<br><br><br>';
        echo $html;
    }
 ?>