<?php
// generate services section
function advisory_generate_csar_form_services() {
	if (is_admin() && is_edit_page()) {
		$id = @$_GET['post'];
		$meta = get_post_meta($id, 'form_opts', true);
		$data = [];
		$data[] = ['type' => 'notice', 'class' => 'danger', 'content' => 'Create "Areas" and save. Then create contents for each area.'];
		if (!empty($meta['areas'])) {
			foreach ($meta['areas'] as $domain) {
				$data[] = array(
					'id' => advisory_id_from_string($domain['name']) . '_services',
					'type' => 'group',
					'title' => $domain['name'],
					'desc' => 'Each Area name should be unique',
					'button_title' => 'Add New',
					'accordion_title' => 'Add New Area',
					'fields' => [['id' => 'name', 'type' => 'text', 'title' => 'Name']],
				);
			}
		}
		return $data;
	}
}
function advisory_generate_csar_form_contents2() {
	if (is_admin() && is_edit_page()) {
		$id = @$_GET['post'];
		$meta = get_post_meta($id, 'form_opts', true);
		$data = [];
		$data[] = ['type' => 'notice', 'class' => 'danger', 'content' => 'Create "Contents" and save.'];
			// 'content' => help($meta, false)
		if (!empty($meta['areas'])) {
			foreach ($meta['areas'] as $domain) {
				$servicesID = advisory_id_from_string($domain['name']) . '_services';
				$data[] = ['type' => 'heading', 'class' => 'danger', 'content' => $domain['name']];
				if ($meta[$servicesID]) {
					foreach ($meta[$servicesID] as $area) {
						$contentID = $servicesID .'_'.advisory_id_from_string($area['name']);
						$data[] = [
							'id' => $contentID,
							'type' => 'group',
							'title' => $area['name'],
							'desc' => 'Domain : ( '. $domain['name'] .' )',
							'button_title' => 'Add New',
							'accordion_title' => 'Add New Content',
							'fields' => [['id' => 'name', 'type' => 'text', 'title' => 'Name'],['id' => 'desc', 'type' => 'textarea', 'title' => 'Description']]
						];
					}
				}
			}
		}
		return $data;
	}
}

function getActiveCSARClass($value=0) {
	$data = ['baseline' => '', 'evolving' => '', 'intermediate' => '', 'advanced' => '', 'innovative' => ''];
	switch ($value) {
		case 5: $data['innovative'] 	= 'active'; break;
		case 4: $data['advanced'] 		= 'active'; break;
		case 3: $data['intermediate'] 	= 'active'; break;
		case 2: $data['evolving'] 		= 'active'; break;
		case 1: $data['baseline'] 		= 'active'; break;
		default: break;
	}
	return $data;
}
// generate content section
function advisory_generate_csar_form_contents($domain) {
	$data = [];
	// DOMAIN 1
	$data['domain_1'][advisory_id_from_string('Oversight')] = [
		'baseline' 		=> '<p>Designated members of management are held accountable by the board or an appropriate board committee for implementing and managing the information security and business continuity programs.</p><p>Information security risks are discussed in management meetings when prompted by highly visible cyber events or regulatory alerts.</p><p>Management provides a written report on the overall status of the information security and business continuity programs to the board or an appropriate board committee at least annually.</p><p>The budgeting process includes information security related expenses and tools.</p>',
		'evolving' 		=> '<p>At least annually, the board or an appropriate board committee reviews and approves the institution’s cybersecurity program. </p><p>Management is responsible for ensuring compliance with legal and regulatory requirements related to cybersecurity. Cybersecurity tools and staff are requested through the budget process.</p><p>There is a process to formally discuss and estimate potential expenses associated with cybersecurity incidents as part of the budgeting process.</p>',
		'intermediate' 	=> '<p>The board or an appropriate board committee has cybersecurity expertise or engages experts to assist with oversight responsibilities.</p><p>The standard board meeting package includes reports and metrics that go beyond events and incidents to address threat intelligence trends and the institution’s security posture.</p><p>The institution has a cyber risk appetite statement approved by the board or an appropriate board committee.</p><p>Cyber risks that exceed the risk appetite are escalated to management.</p><p>The board or an appropriate board committee ensures management’s annual cybersecurity self-assessment evaluates the institution’s ability to meet its cyber risk management standards.</p><p>The board or an appropriate board committee reviews and approves management’s prioritization and resource allocation decisions based on the results of the cyber assessments.</p><p>The board or an appropriate board committee ensures management takes appropriate actions to address changing cyber risks or significant cybersecurity issues.</p><p>The budget process for requesting additional cybersecurity staff and tools is integrated into business units’ budget processes. </p>',
		'advanced' 		=> '<p>The board or board committee approved cyber risk appetite statement is part of the enterprise-wide risk appetite statement.</p><p>Management has a formal process to continuously improve cybersecurity oversight.</p><p>The budget process for requesting additional cybersecurity staff and tools maps current resources and tools to the cybersecurity strategy. </p><p>Management and the board or an appropriate board committee hold business units accountable for effectively managing all cyber risks associated with their activities.</p><p>Management identifies root cause(s) when cyber attacks result in material loss. </p><p>The board or an appropriate board committee ensures that management’s actions consider the cyber risks that the institution poses to the financial sector</p>',
		'innovative' 	=> '<p>The board or an appropriate board committee discusses ways for management to develop cybersecurity improvements that may be adopted sector-wide.</p><p>The board or an appropriate board committee verifies that management’s actions consider the cyber risks that the institution poses to other critical infrastructures (e.g., telecommunications, energy).</p>',
	];
	$data['domain_1'][advisory_id_from_string('Strategy/Policies')] = [
		'baseline' 		=> '<p>The institution has an information security strategy that integrates technology, policies, procedures, and training to mitigate risk. 
			</p><p>The institution has policies commensurate with its risk and complexity that address the concepts of information technology risk management. </p><p>The institution has policies commensurate with its risk and complexity that address the concepts of threat information sharing.</p><p>The institution has board-approved policies commensurate with its risk and complexity that address information security.</p><p>The institution has policies commensurate with its risk and complexity that address the concepts of external dependency or third-party management.</p><p>The institution has policies commensurate with its risk and complexity that address the concepts of incident response and resilience.</p><p>All elements of the information security program are coordinated enterprisewide.</p>',
		'evolving' 		=> '<p>The institution augmented its information security strategy to incorporate cybersecurity and resilience.</p><p>The institution has a formal cybersecurity program that is based on technology and security industry standards or benchmarks. </p><p>A formal process is in place to update policies as the institution’s inherent risk profile changes </p>',
		'intermediate' 	=> '<p>The institution has a comprehensive set of policies commensurate with its risk and complexity that address the concepts of threat intelligence.</p><p>Management periodically reviews the cybersecurity strategy to address evolving cyber threats and changes to the institution’s inherent risk profile.</p><p>The cybersecurity strategy is incorporated into, or conceptually fits within, the institution’s enterprise-wide risk management strategy.</p><p>Management links strategic cybersecurity objectives to tactical goals.</p><p>A formal process is in place to cross-reference and simultaneously update all policies related to cyber risks across business lines.</p>',
		'advanced' 		=> '<p>The cybersecurity strategy outlines the institution’s future state of cybersecurity with short-term and long-term perspectives.</p><p>Industry-recognized cybersecurity standards are used as sources during the analysis of cybersecurity program gaps.</p><p>The cybersecurity strategy identifies and communicates the institution’s role as a component of critical infrastructure in the financial services industry.</p><p>The risk appetite is informed by the institution’s role in critical infrastructure. </p><p>Management is continuously improving the existing cybersecurity program to adapt as the desired cybersecurity target state changes</p>',
		'innovative' 	=> '<p>The cybersecurity strategy identifies and communicates the institution’s role as it relates to other critical infrastructures.</p>',
	];
	$data['domain_1'][advisory_id_from_string('IT Asset Management')] = [
		'baseline' 		=> '<p>An inventory of organizational assets (e.g., hardware, software, data, and systems hosted externally) is maintained.</p><p>Organizational assets (e.g., hardware, systems, data, and applications) are prioritized for protection based on the data classification and business value.</p><p>Management assigns accountability for maintaining an inventory of organizational assets.</p><p>A change management process is in place to request and approve changes to systems configurations, hardware, software, applications, and security tools</p>',
		'evolving' 		=> '<p>The asset inventory, including identification of critical assets, is updated at least annually to address new, relocated,re-purposed,and sunset assets.</p><p>The institution proactively manages system EOL (e.g., replacement) to limit security risks.</p><p>Changes are formally approved by an individual or committee with appropriate authority and with separation of duties</p>',
		'intermediate' 	=> '<p>Baseline configurations cannot be altered without a formal change request, documented approval, and an assessment of security implications.</p><p>A formal IT change management process requires cybersecurity risk to be evaluated during the analysis, approval, testing, and reporting of changes.</p>',
		'advanced' 		=> '<p>Supply chain risk is reviewed before the acquisition of mission-critical information systems including system components.</p><p>Automated tools enable tracking, updating, asset prioritizing, and custom reporting of the asset inventory.</p><p>Automated processes are in place to detect and block unauthorized changes to software and hardware. </p><p>The change management system uses thresholds to determine when a risk assessment of the impact of the change is required</p>',
		'innovative' 	=> '<p>A formal change management function governs decentralized or highly distributed change requests and identifies and measures security risks that may cause increased exposure to cyber attack.</p><p>Comprehensive automated enterprise tools are implemented to detect and block unauthorized changes to software and hardware.</p>',
	];
	$data['domain_1'][advisory_id_from_string('Risk Management Program')] = [
		'baseline' 		=> '<p>An information security and business continuity risk management function(s) exists within the institution</p>',
		'evolving' 		=> '<p>The risk management program incorporates cyber risk identification, measurement, mitigation, monitoring, and reporting.</p><p>Management reviews and uses the results of audits to improve existing cybersecurity policies, procedures, and controls. </p><p>Management monitors moderate and high residual risk issues from the cybersecurity risk assessment until items are addressed.</p>',
		'intermediate' 	=> '<p>The cybersecurity function has a clear reporting line that does not present a conflict of interest.</p><p>The risk management program specifically addresses cyber risks beyond the boundaries of the technological impacts (e.g., financial, strategic, regulatory, compliance).</p><p>Benchmarks or target performance metrics have been established for showing improvements or regressions of the security posture over time. </p><p>Management uses the results of independent audits and reviews to improve cybersecurity. </p><p>There is a process to analyze and assign potential losses and related expenses, by cost center, associated with cybersecurity incidents. </p>',
		'advanced' 		=> '<p>Cybersecurity metrics are used to facilitate strategic decision-making and funding in areas of need.</p><p>Independent risk management sets and monitors cyber-related risk limits for business units.</p><p>Independent risk management staff escalates to management and the board or an appropriate board committee significant discrepancies from business unit’s assessments of cyber-related risk. </p><p>A process is in place to analyze the financial impact cyber incidents have on the institution’s capital. </p><p>The cyber risk data aggregation and real-time reporting capabilities support the institution’s ongoing reporting needs, particularly during cyber incidents</p>',
		'innovative' 	=> '<p>The risk management function identifies and analyzes commonalities in cyber events that occur both at the institution and across other sectors to enable more predictive risk management.</p><p>A process is in place to analyze the financial impact that a cyber incident at the institution may have across the financial sector. </p>',
	];
	$data['domain_1'][advisory_id_from_string('Risk Assessment')] = [
		'baseline' 		=> '<p>A risk assessment focused on safeguarding customer information identifies reasonable and foreseeable internal and external threats, the likelihood and potential damage of threats, and the sufficiency of policies, procedures, and customer information systems.</p><p>The risk assessment identifies internet-based systems and high-risk transactions that warrant additional authentication controls.</p><p>The risk assessment is updated to address new technologies, products, services, and connections before deployment.</p>',
		'evolving' 		=> '<p>Risk assessments are used to identify the cybersecurity risks stemming from new products, services, or relationships.</p><p>The focus of the risk assessment has expanded beyond customer information to address all information assets.</p><p>The risk assessment considers the risk of using EOL software and hardware components.</p>',
		'intermediate' 	=> '<p>The risk assessment is adjusted to consider widely known risks or risk management practices.</p>',
		'advanced' 		=> '<p>An enterprise-wide risk management function incorporates cyber threat analysis and specific risk exposure as part of the enterprise risk assessment.</p>',
		'innovative' 	=> '<p>The risk assessment is updated in real time as changes to the risk profile occur, new applicable standards are released or updated, and new exposures are anticipated.</p><p>The institution uses information from risk assessments to predict threats and drive real-time responses. </p><p>Advanced or automated analytics offer predictive information and real-time risk metrics.</p>',
	];
	$data['domain_1'][advisory_id_from_string('Audit')] = [
		'baseline' 		=> '<p>Independent audit or review evaluates policies, procedures, and controls across the institution for significant risks and control issues associated with the institution\'s operations, including risks in new products, emerging technologies, and information systems.</p><p>The independent audit function validates controls related to the storage or transmission of confidential data.</p><p>Logging practices are independently reviewed periodically to ensure appropriate log management (e.g., access controls, retention, and maintenance).</p><p>Issues and corrective actions from internal audits and independent testing/assessments are formally tracked to ensure procedures and control lapses are resolved in a timely manner.</p>',
		'evolving' 		=> '<p>The independent audit function validates that the risk management function is commensurate with the institution’s risk and complexity.</p><p>The independent audit function validates that the institution’s threat information sharing is commensurate with the institution’s risk and complexity.</p><p>The independent audit function validates that the institution’s cybersecurity controls function is commensurate with the institution’s risk and complexity.</p><p>The independent audit function validates that the institution’s third-party relationship management is commensurate with the institution’s risk and complexity.</p><p>The independent audit function validates that the institution’s incident response program and resilience are commensurate with the institution’s risk and complexity.</p>',
		'intermediate' 	=> '<p>A formal process is in place for the independent audit function to update its procedures based on changes to the institution’s inherent risk profile.</p><p>The independent audit function validates that the institution’s threat intelligence and collaboration are commensurate with the institution’s risk and complexity.</p><p>The independent audit function regularly reviews management’s cyber risk appetite statement.</p><p>Independent audits or reviews are used to identify gaps in existing security capabilities and expertise.</p>',
		'advanced' 		=> '<p>A formal process is in place for the independent audit function to update its procedures based on changes to the evolving threat landscape across the sector.</p><p>The independent audit function regularly reviews the institution’s cyber risk appetite statement in comparison to assessment results and incorporates gaps into the audit strategy.</p><p>Independent audits or reviews are used to identify cybersecurity weaknesses, root causes, and the potential impact to business units.</p>',
		'innovative' 	=> '<p>A formal process is in place for the independent audit function to update its procedures based on changes to the evolving threat landscape across other sectors the institution depends upon.</p><p>The independent audit function uses sophisticated data mining tools to perform continuous monitoring of cybersecurity processes or controls.</p>',
	];
	$data['domain_1'][advisory_id_from_string('Staffing')] = [
		'baseline' 		=> '<p>Information security roles and responsibilities have been identified.</p><p>Processes are in place to identify additional expertise needed to improve information security defenses.</p>',
		'evolving' 		=> '<p>A formal process is used to identify cybersecurity tools and expertise that may be needed.</p>
		<p>Management with appropriate knowledge and experience leads the institutions cybersecurity efforts.</p><p>Staff with cybersecurity responsibilities have the requisite qualifications to perform the necessary tasks of the position.</p><p>Employment candidates, contractors, and third parties are subject to background verification proportional to the confidentiality of the data accessed, business requirements, and acceptable risk.</p>',
		'intermediate' 	=> '<p>The institution has a program for talent recruitment, retention, and succession planning for the cybersecurity and resilience staffs.</p>',
		'advanced' 		=> '<p>The institution benchmarks its cybersecurity staffing against peers to identify whether its recruitment, retention, and succession planning are commensurate.</p><p>Dedicated cybersecurity staff develops, or contributes to developing, integrated enterprise-level security and cyber defense strategies.</p>',
		'innovative' 	=> '<p>The institution actively partners with industry associations and academia to inform curricula based on future cybersecurity staffing needs of the industry</p>',
	];
	$data['domain_1'][advisory_id_from_string('Training')] = [
		'baseline' 		=> '<p>Annual information security training is provided.</p><p>Annual information security training includes incident response, current cyber threats (e.g., phishing, spear phishing, social engineering, and mobile security), and emerging issues.</p><p>Situational awareness materials are made available to employees when prompted by highly visible cyber events or by regulatory alerts.</p><p>Customer awareness materials are readily available (e.g., DHS’ Cybersecurity Awareness Month materials).</p>',
		'evolving' 		=> '<p>The institution has a program for continuing cybersecurity training and skill development for cybersecurity staff.</p><p>Management is provided cybersecurity training relevant to their job responsibilities.</p><p>Employees with privileged account permissions receive additional cybersecurity training commensurate with their levels of responsibility.</p><p>Business units are provided cybersecurity training relevant to their particular business risks.</p><p>The institution validates the effectiveness of training (e.g., social engineering or phishing tests).</p>',
		'intermediate' 	=> '<p>Management incorporates lessons learned from social engineering and phishing exercises to improve the employee awareness programs.</p><p>Cybersecurity awareness information is provided to retail customers and commercial clients at least annually.</p><p>Business units are provided cybersecurity training relevant to their particular business risks, over and above what is required of the institution as a whole.</p><p>
		The institution routinely updates its training to security staff to adapt to new threats. </p>',
		'advanced' 		=> '<p>Independent directors are provided with cybersecurity training that addresses how complex products, services, and lines of business affect the institutions cyber risk.</p>',
		'innovative' 	=> '<p>Key performance indicators are used to determine whether training and awareness programs positively influence behavior.</p>',
	];
	$data['domain_1'][advisory_id_from_string('Culture')] = [
		'baseline' 		=> '<p>Management holds employees accountable for complying with the information security program. </p>',
		'evolving' 		=> '<p>The institution has formal standards of conduct that hold all employees accountable for complying with cybersecurity policies and procedures.</p><p>Cyber risks are actively discussed at business unit meetings. </p><p>Employees have a clear understanding of how to identify and escalate potential cybersecurity issues.</p>',
		'intermediate' 	=> '<p>Management ensures performance plans are tied to compliance with cybersecurity policies and standards in order to hold employees accountable.</p><p>The risk culture requires formal consideration of cyber risks in all business decisions.</p><p>Cyber risk reporting is presented and discussed at the independent risk management meetings </p>',
		'advanced' 		=> '<p>Management ensures continuous improvement of cyber risk cultural awareness.</p>',
		'innovative' 	=> '<p>The institution leads efforts to promote cybersecurity culture across the sector and to other sectors that they depend upon.</p>',
	];
	// DOMAIN 2
	$data['domain_2'][advisory_id_from_string('Information Sharing')] = [
		'baseline' 		=> '<p>Information security threats are gathered and shared with applicable internal employees.</p> <p>Contact information for law enforcement and the regulator(s) is maintained and updated regularly.</p> <p>Information about threats is shared with law enforcement and regulators when required or prompted.</p>',
		'evolving' 		=> '<p>A formal and secure process is in place to share threat and vulnerability information with other entities.</p> <p>A representative from the institution participates in law enforcement or information-sharing organization meetings.</p>',
		'intermediate' 	=> '<p>A formal protocol is in place for sharing threat, vulnerability, and incident information to employees based on their specific job function.</p> <p>Information-sharing agreements are used as needed or required to facilitate sharing threat information with other financial sector organizations or third parties.</p> <p>Information is shared proactively with the industry, law enforcement, regulators, and information-sharing forums.</p> <p>A process is in place to communicate and collaborate with the public sector regarding cyber threats.</p>',
		'advanced' 		=> '<p>Management communicates threat intelligence with business risk context and specific risk management recommendations to the business units.</p> <p>Relationships exist with employees of peer institutions for sharing cyber threat intelligence.</p> <p>A network of trust relationships (formal and/or informal) has been established to evaluate information about cyber threats.</p>',
		'innovative' 	=> '<p>A mechanism is in place for sharing cyber threat intelligence with business units in real time including the potential financial and operational impact of inaction.</p> <p>A system automatically informs management of the level of business risk specific to the institution and the progress of recommended steps taken to mitigate the risks.</p> <p>The institution is leading efforts to create new sector-wide informationsharing channels to address gaps in external-facing information-sharing mechanisms.</p>',
	];
	$data['domain_2'][advisory_id_from_string('Monitoring And Analyzing')] = [
		'baseline' 		=> '<p>Audit log records and other security event logs are reviewed and retained in a secure manner.</p><p>Computer event logs are used for investigations once an event has occurred.</p>',
		'evolving' 		=> '<p>A process is implemented to monitor threat information to discover emerging threats.</p><p>The threat information and analysis process is assigned to a specific group or individual.</p><p>Security processes and technology are centralized and coordinated in a Security Operations Center (SOC) or equivalent.</p><p>Monitoring systems operate continuously with adequate support for efficient incident handling.</p>',
		'intermediate' 	=> '<p>A threat intelligence team is in place that evaluates threat intelligence from multiple sources for credibility, relevance, and exposure.</p><p>A profile is created for each threat that identifies the likely intent, capability, and target of the threat.</p><p>Threat information sources that address all components of the threat profile are prioritized and monitored.</p><p>Threat intelligence is analyzed to develop cyber threat summaries including risks to the institution and specific actions for the institution to consider.</p>',
		'advanced' 		=> '<p>A dedicated cyber threat identification and analysis committee or team exists to centralize and coordinate initiatives and communications.</p><p>Formal processes have been defined to resolve potential conflicts in information received from sharing and analysis centers or other sources.</p><p>Emerging internal and external threat intelligence and correlated log analysis are used to predict future attacks.</p><p>Threat intelligence is viewed within the context of the institutions risk profile and risk appetite to prioritize mitigating actions in anticipation of threats.</p><p>Threat intelligence is used to update architecture and configuration standards.</p>',
		'innovative' 	=> '<p>The institution uses multiple sources of intelligence, correlated log analysis, alerts, internal traffic flows, and geopolitical events to predict potential future attacks and attack trends.</p><p>Highest risk scenarios are used to predict threats against specific business targets.</p><p>IT systems automatically detect configuration weaknesses based on threat intelligence and alert management so actions can be prioritized.</p>',
	];
	$data['domain_2'][advisory_id_from_string('Threat Intelligence And Information')] = [
		'baseline' 		=> '<p>The institution belongs or subscribes to a threat and vulnerability information sharing source(s) that provides information on threats (e.g., Financial Services Information Sharing and Analysis Center.</p> <p>Threat information is used to monitor threats and vulnerabilities.</p> <p>Threat information is used to enhance internal risk management and controls.</p>',
		'evolving' 		=> '<p>Threat information received by the institution includes analysis of tactics, patterns, and risk mitigation recommendations.</p>',
		'intermediate' 	=> '<p>A formal threat intelligence program is implemented and includes subscription to threat feeds from external providers and internal sources.</p> <p>Protocols are implemented for collecting information from industry peers and government.</p> <p>A read-only, central repository of cyber threat intelligence is maintained.</p>',
		'advanced' 		=> '<p>A cyber intelligence model is used for gathering threat information.</p> <p>Threat intelligence is automatically received from multiple sources in real time.</p> <p>The institution’s threat intelligence includes information related to geopolitical events that could increase cybersecurity threat levels.</p>',
		'innovative' 	=> '<p>A threat analysis system automatically correlates threat data to specific risks and then takes risk-based automated actions while alerting management.</p> <p>The institution is investing in the development of new threat intelligence and collaboration mechanisms (e.g., technologies, business processes) that will transform how information is gathered and shared.</p>',
	];
	// DOMAIN 3
	$data['domain_3'][advisory_id_from_string('Access And Data Management')] = [
		'baseline' 		=> '<p>Employee access is granted to systems and confidential data based on job responsibilities and the principles of least privilege.</p> <p>Employee access to systems and confidential data provides for separation of duties.</p> <p>Elevated privileges (e.g., administrator privileges) are limited and tightly controlled (e.g., assigned to individuals, not shared, and require stronger password controls).</p> <p>User access reviews are performed periodically for all systems and applications based on the risk to the application or system.</p> <p>Changes to physical and logical user access, including those that result from voluntary and involuntary terminations, are submitted to and approved by appropriate personnel.</p> <p>Identification and authentication are required and managed for access to systems, applications, and hardware.</p> <p>Access controls include password complexity and limits to password attempts and reuse.</p> <p>All default passwords and unnecessary default accounts are changed before system implementation.</p> <p>Customer access to Internet-based products or services requires authentication controls (e.g., layered controls, multifactor) that are commensurate with the risk.</p> <p>Production and non-production environments are segregated to prevent unauthorized access or changes to information assets. (*N/A if no production environment exists at the institution or the institution’s third party.)</p> <p>Physical security controls are used to prevent unauthorized access to information systems and telecommunication systems.</p> <p>All passwords are encrypted in storage and in transit.</p> <p>Confidential data are encrypted when transmitted across public or untrusted networks (e.g., Internet).</p> <p>Mobile devices (e.g., laptops, tablets, and removable media) are encrypted if used to store confidential data. (*N/A if mobile devices are not used.)</p> <p>Remote access to critical systems by employees, contractors, and third parties uses encrypted connections and multifactor authentication.</p> <p>Administrative, physical, or technical controls are in place to prevent users without administrative responsibilities from installing unauthorized software.</p> <p>Customer service (e.g., the call center) utilizes formal procedures to authenticate customers commensurate with the risk of the transaction or request.</p> <p>Data is disposed of or destroyed according to documented requirements and within expected time frames.</p>',
		'evolving' 		=> '<p>Changes to user access permissions trigger automated notices to appropriate personnel.</p> <p>Administrators have two accounts: one for administrative use and one for general purpose, non-administrative tasks.</p> <p>Use of customer data in non-production environments complies with legal, regulatory, and internal policy requirements for concealing or removing of sensitive data elements.</p> <p>Physical access to high-risk or confidential systems is restricted, logged, and unauthorized access is blocked.</p> <p>Controls are in place to prevent unauthorized access to cryptographic keys.</p>',
		'intermediate' 	=> '<p>The institution has implemented tools to prevent unauthorized access to or exfiltration of confidential data.</p> <p>Controls are in place to prevent unauthorized escalation of user privileges.</p> <p>Access controls are in place for database administrators to prevent unauthorized downloading or transmission of confidential data.</p> <p>All physical and logical access is removed immediately upon notification of involuntary termination and within 24 hours of an employee’s voluntary departure.</p> <p>Multifactor authentication and/or layered controls have been implemented to secure all third-party access to the institutions network and/or systems and applications.</p> <p>Multifactor authentication (e.g., tokens, digital certificates) techniques are used for employee access to high-risk systems as identified in the risk assessment(s). (*N/A if no high risk systems.)</p> <p>Confidential data are encrypted in transit across private connections (e.g., frame relay and T1) and within the institution’s trusted zones.</p> <p>Controls are in place to prevent unauthorized access to collaborative computing devices and applications (e.g., networked white boards, cameras, microphones, online applications such as instant messaging and document sharing).</p>',
		'advanced' 		=> '<p>Encryption of select data at rest is determined by the institution’s data classification and risk assessment.</p> <p>Customer authentication for high-risk transactions includes methods to prevent malware and man-in-the-middle attacks (e.g., using visual transaction signing).</p>',
		'innovative' 	=> '<p>Adaptive access controls de-provision or isolate an employee, third-party, or customer credentials to minimize potential damage if malicious behavior is suspected.</p> <p>Unstructured confidential data are tracked and secured through an identity-aware, cross-platform storage system that protects against internal threats, monitors user access, and tracks changes.</p> <p>Tokenization is used to substitute unique values for confidential information (e.g., virtual credit card).</p> <p>The institution is leading efforts to create new technologies and processes for managing customer, employee, and third-party authentication and access.</p> <p>Real-time risk mitigation is taken based on automated risk scoring of user credentials.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Anomalous Activity Detection')] = [
		'baseline' 		=> '<p>The institution is able to detect anomalous activities through monitoring across the environment.</p> <p>Customer transactions generating anomalous activity alerts are monitored and reviewed.</p> <p>Logs of physical and/or logical access are reviewed following events.</p> <p>Access to critical systems by third parties is monitored for unauthorized or unusual activity.</p> <p>Elevated privileges are monitored.</p>
',
		'evolving' 		=> '<p>Systems are in place to detect anomalous behavior automatically during customer, employee, and third-party authentication.</p> <p>Security logs are reviewed regularly.</p> <p>Logs provide traceability for all system access by individual users.</p> <p>Thresholds have been established to determine activity within logs that would warrant management response.</p>',
		'intermediate' 	=> '<p>Online customer transactions are actively monitored for anomalous behavior.</p> <p>Tools to detect unauthorized data mining are used.</p> <p>Tools actively monitor security logs for anomalous behavior and alert within established parameters.</p> <p>Audit logs are backed up to a centralized log server or media that is difficult to alter.</p> <p>Thresholds for security logging are evaluated periodically.</p> <p>Anomalous activity and other network and system alerts are correlated across business units to detect and prevent multifaceted attacks (e.g., simultaneous account takeover and DDoS attack).</p>',
		'advanced' 		=> '<p>logins occur within a short period of time but from physically distant IP locations.</p> <p>External transfers from customer accounts generate alerts and require review and authorization if anomalous behavior is detected.</p> <p>A system is in place to monitor and analyze employee behavior (network use patterns, work hours, and known devices) to alert on anomalous activities.</p> <p>An automated tool(s) is in place to detect and prevent data mining by insider threats. Tags on fictitious confidential data or files are used to provide advanced alerts of potential malicious activity when the data is accessed</p>',
		'innovative' 	=> '<p>The institution has a mechanism for real-time automated risk scoring of threats.</p> <p>The institution is developing new technologies that will detect potential insider threats and block activity in real time.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Device_end-Point Security')] = [
		'baseline' 		=> '<p>Controls are in place to restrict the use of removable media to authorized personnel</p>',
		'evolving' 		=> '<p>Tools automatically block attempted access from unpatched employee and third-party devices.</p> <p>Tools automatically block attempted access by unregistered devices to internal networks.</p> <p>The institution has controls to prevent the unauthorized addition of new connections.</p> <p>Controls are in place to prevent unauthorized individuals from copying confidential data to removable media.</p> <p>Antivirus and anti-malware tools are deployed on end-point devices (e.g., workstations, laptops, and mobile devices).</p> <p>Mobile devices with access to the institution’s data are centrally managed for antivirus and patch deployment. (*N/A if mobile devices are not used.)</p> <p>The institution wipes data remotely on mobile devices when a device is missing or stolen. (*N/A if mobile devices are not used.)</p>
',
		'intermediate' 	=> '<p>Data loss prevention controls or devices are implemented for inbound and outbound communications (e.g., e-mail, FTP, Telnet, prevention of large file transfers).</p> <p>Mobile device management includes integrity scanning (e.g., jailbreak/rooted detection). (*N/A if mobile devices are not used.)</p> <p>Mobile devices connecting to the corporate network for storing and accessing company information allow for remote software version/patch validation.</p>',
		'advanced' 		=> '<p>Employees’ and third parties’ devices (including mobile) without the latest security patches are quarantined and patched before the device is granted access to the network.</p> <p>Confidential data and applications on mobile devices are only accessible via a secure, isolated sandbox or a secure container.</p>',
		'innovative' 	=> '<p>A centralized end-point management tool provides fully integrated patch, configuration, and vulnerability management, while also being able to detect malware upon arrival to prevent an exploit.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Event Detection')] = [
		'baseline' 		=> '<p>A normal network activity baseline is established.</p><p>Mechanisms (e.g., antivirus alerts, log event alerts) are in place to alert management to potential attacks.</p><p>Processes are in place to monitor for the presence of unauthorized users, devices, connections, and software.</p><p>Responsibilities for monitoring and reporting suspicious systems activity have been assigned.</p><p>The physical environment is monitored to detect potential unauthorized access.</p>',
		'evolving' 		=> '<p>A process is in place to correlate event information from multiple sources (e.g., network, application, or firewall).</p><p>INTERMEDIATE</p><p>Controls or tools (e.g., data loss prevention) are in place to detect potential unauthorized or unintentional transmissions of confidential data.</p><p>Event detection processes are proven reliable.</p><p>Specialized security monitoring is used for critical assets throughout the infrastructure.</p>',
		'intermediate' 	=> 'dolor',
		'advanced' 		=> '<p>Automated tools detect unauthorized changes to critical system files, firewalls, IPS, IDS, or other security devices.</p><p>Real-time network monitoring and detection is implemented and incorporates sector-wide event information.</p><p>Real-time alerts are automatically sent when unauthorized software, hardware, or changes occur.</p><p>Tools are in place to actively correlate event information from multiple sources and send alerts based on established parameters.</p>',
		'innovative' 	=> '<p>The institution is leading efforts to develop event detection systems that will correlate in real time when events are about to occur.</p><p>The institution is leading the development effort to design new technologies that will detect potential insider threats and block activity in real time.</p>
',
	];
	$data['domain_3'][advisory_id_from_string('Infrastructure And Management')] = [
		'baseline' 		=> '<p>Network perimeter defense tools (e.g., border router and firewall) are used.</p><p>Systems that are accessed from the Internet or by external parties are protected by firewalls or other similar devices.</p><p>All ports are monitored.</p><p>Up to date antivirus and anti-malware tools are used.</p><p>Systems configurations (for servers, desktops, routers, etc.) follow industry standards and are enforced.</p><p>Ports, functions, protocols and services are prohibited if no longer needed for business purposes.</p><p>Access to make changes to systems configurations (including virtual machines and hypervisors) is controlled and monitored.</p><p>Programs that can override system, object, network, virtual machine, and application controls are restricted.</p><p>System sessions are locked after a pre-defined period of inactivity and are terminated after pre-defined conditions are met.</p><p>Wireless network environments require security settings with strong encryption for authentication and transmission. (*N/A if there are no wireless networks.)</p>',
		'evolving' 		=> '<p>There is a firewall at each Internet connection and between any Demilitarized Zone (DMZ) and internal network(s).</p><p>Antivirus and intrusion detection/prevention systems (IDS/IPS) detect and block actual and attempted attacks or intrusions.</p><p>Technical controls prevent unauthorized devices, including rogue wireless access devices and removable media, from connecting to the internal network(s).</p><p>A risk-based solution is in place at the institution or Internet hosting provider to mitigate disruptive cyber attacks (e.g., DDoS attacks).</p><p>Guest wireless networks are fully segregated from the internal network(s). (*N/A if there are no wireless networks.)</p><p>Domain Name System Security Extensions (DNSSEC) is deployed across the enterprise.</p><p>Critical systems supported by legacy technologies are regularly reviewed to identify for potential vulnerabilities, upgrade opportunities, or new defense layers.</p><p>Controls for unsupported systems are implemented and tested.</p>
',
		'intermediate' 	=> '<p>The enterprise network is segmented in multiple, separate trust/security zones with defense-in-depth strategies (e.g., logical network segmentation, hard backups, air-gapping) to mitigate attacks.</p><p>Security controls are used for remote access to all administrative consoles, including restricted virtual systems.</p><p>Wireless network environments have perimeter firewalls that are implemented and configured to restrict unauthorized traffic. (*N/A if there are no wireless networks.)</p><p>Wireless networks use strong encryption with encryption keys that are changed frequently. (*N/A if there are no wireless networks.)</p><p>The broadcast range of the wireless network(s) is confined to institutioncontrolled boundaries. (*N/A if there are no wireless networks.)</p><p>Technical measures are in place to prevent the execution of unauthorized code on institution owned or managed devices, network infrastructure, and systems components.</p>',
		'advanced' 		=> '<p>Network environments and virtual instances are designed and configured to restrict and monitor traffic between trusted and untrusted zones.</p><p>Only one primary function is permitted per server to prevent functions that require different security levels from co-existing on the same server.</p><p>Anti-spoofing measures are in place to detect and block forged source IP addresses from entering the network.</p>
',
		'innovative' 	=> '<p>The institution risk scores all of its infrastructure assets and updates in real time based on threats, vulnerabilities, or operational changes.</p><p>Automated controls are put in place based on risk scores to infrastructure assets, including automatically disconnecting affected assets.</p><p>The institution proactively seeks to identify control gaps that may be used as part of a zero-day attack.</p><p>Public-facing servers are routinely rotated and restored to a known clean state to limit the window of time a system is exposed to potential threats</p>',
	];
	$data['domain_3'][advisory_id_from_string('Patch Management')] = [
		'baseline' 		=> '<p>A patch management program is implemented and ensures that software and firmware patches are applied in a timely manner.</p> <p>Patches are tested before being applied to systems and/or software.</p> <p>Patch management reports are reviewed and reflect missing security patches.</p>',
		'evolving' 		=> '<p>A formal process is in place to acquire, test, and deploy software patches based on criticality.</p> <p>Systems are configured to retrieve patches automatically.</p> <p>Operational impact is evaluated before deploying security patches.</p> <p>An automated tool(s) is used to identify missing security patches as well as the number of days since each patch became available.</p> <p>Missing patches across all environments are prioritized and tracked.</p> ',
		'intermediate' 	=> '<p>Patches for high-risk vulnerabilities are tested and applied when released or the risk is accepted and accountability assigned.</p>',
		'advanced' 		=> '
<p>Patch monitoring software is installed on all servers to identify any missing patches for the operating system software, middleware, database, and other key software.</p> <p>The institution monitors patch management reports to ensure security patches are tested and implemented within aggressive time frames (e.g., 0-30 days).</p>',
		'innovative' 	=> '<p>The institution develops security patches or bug fixes or contributes to open source code development for systems it uses.</p> <p>Segregated or separate systems are in place that mirror production systems allowing for rapid testing and implementation of patches and provide for rapid fallback when needed.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Remediation')] = [
		'baseline' 		=> '<p>Issues identified in assessments are prioritized and resolved based on criticality and within the time frames established in the response to the assessment report.</p>
',
		'evolving' 		=> '<p>Data is destroyed or wiped on hardware and portable/mobile media when a device is missing, stolen, or no longer needed.</p> <p>Formal processes are in place to resolve weaknesses identified during penetration testing</p>
',
		'intermediate' 	=> '<p>Remediation efforts are confirmed by conducting a follow-up vulnerability scan.</p> <p>Penetration testing is repeated to confirm that medium- and high-risk, exploitable vulnerabilities have been resolved.</p> <p>Security investigations, forensic analysis, and remediation are performed by qualified staff or third parties.</p> <p>Generally accepted and appropriate forensic procedures, including chain of custody, are used to gather and present evidence to support potential legal action.</p> <p>The maintenance and repair of organizational assets are performed by authorized individuals with approved and controlled tools.</p> <p>The maintenance and repair of organizational assets are logged in a timely manner.</p>',
		'advanced' 		=> '<p>All medium and high risk issues identified in penetration testing, vulnerability scanning, and other independent testing are escalated to the board or an appropriate board committee for risk acceptance if not resolved in a timely manner.</p>
',
		'innovative' 	=> '<p>The institution is developing technologies that will remediate systems damaged by zero-day attacks to maintain current recovery time objectives.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Secure Coding')] = [
		'baseline' 		=> '<p>Developers working for the institution follow secure program coding practices, as part of a system development life cycle (SDLC), that meet industry standards.</p> <p>The security controls of internally developed software are periodically reviewed and tested. (*N/A if there is no software development.)</p> <p>The security controls in internally developed software code are independently reviewed before migrating the code to production. (*N/A if there is no software development.)</p> <p>Intellectual property and production code are held in escrow. (*N/A if there is no production code to hold in escrow.)</p>',
		'evolving' 		=> '<p>Security testing occurs at all post-design phases of the SDLC for all applications, including mobile applications. (*N/A if there is no software development.)</p>',
		'intermediate' 	=> '<p>Processes are in place to mitigate vulnerabilities identified as part of the secure development of systems and applications.</p> <p>The security of applications, including Web-based applications connected to the Internet, is tested against known types of cyber attacks (e.g., SQL injection, cross-site scripting, buffer overflow) before implementation or following significant changes.</p> <p>Software code executables and scripts are digitally signed to confirm the software author and guarantee that the code has not been altered or corrupted.</p> <p>A risk-based, independent information assurance function evaluates the security of internal applications.</p>',
		'advanced' 		=> '<p>Vulnerabilities identified through a static code analysis are remediated before implementing newly developed or changed applications into production.</p> <p>All interdependencies between applications and services have been identified.</p> <p>Independent code reviews are completed on internally developed or vendor-provided custom applications to ensure there are no security gaps.</p>',
		'innovative' 	=> '<p>Software code is actively scanned by automated tools in the development environment so that security weaknesses can be resolved immediately during the design phase.</p>',
	];
	$data['domain_3'][advisory_id_from_string('Threat And Vulnerability Detection')] = [
		'baseline' 		=> '<p>Independent testing (including penetration testing and vulnerability scanning) is conducted according to the risk assessment for externalfacing systems and the internal network.</p> <p>Antivirus and anti-malware tools are used to detect attacks.</p> <p>Firewall rules are audited or verified at least quarterly.</p> <p>E-mail protection mechanisms are used to filter for common cyber threats (e.g., attached malware or malicious links).</p>',
		'evolving' 		=> '<p>Independent penetration testing of network boundary and critical Webfacing applications is performed routinely to identify security control gaps.</p> <p>Independent penetration testing is performed on Internet-facing applications or systems before they are launched or undergo significant change.</p> <p>Antivirus and anti-malware tools are updated automatically.</p> <p>Firewall rules are updated routinely.</p> <p>Vulnerability scanning is conducted and analyzed before deployment/redeployment of new/existing devices.</p> <p>Processes are in place to monitor potential insider activity that could lead to data theft or destruction.</p>',
		'intermediate' 	=> '<p>Audit or risk management resources review the penetration testing scope and results to help determine the need for rotating companies based on the quality of the work.</p> <p>E-mails and attachments are automatically scanned to detect malware and are blocked when malware is present.</p>',
		'advanced' 		=> '<p>Weekly vulnerability scanning is rotated among environments to scan all environments throughout the year.</p> <p>Penetration tests include cyber attack simulations and/or real-world tactics and techniques such as red team testing to detect control gaps in employee behavior, security defenses, policies, and resources.</p> <p>Automated tool(s) proactively identifies high-risk behavior signaling an employee who may pose an insider threat.</p>',
		'innovative' 	=> '<p>User tasks and content (e.g., opening an e-mail attachment) are automatically isolated in a secure container or virtual environment so that malware can be analyzed but cannot access vital data, end-point operating systems, or applications on the institution’s network.</p> <p>Vulnerability scanning is performed on a weekly basis across all environments.</p>',
	];
	// DOMAIN 4
	$data['domain_4'][advisory_id_from_string('Connections')] = [
		'baseline' 		=> '<p>The critical business processes that are dependent on external connectivity have been identified.</p> <p>The institution ensures that third-party connections are authorized.</p> <p>A network diagram is in place and identifies all external connections.</p> <p>Data flow diagrams are in place and document information flow to external parties.</p>',
		'evolving' 		=> '<p>Critical business processes have been mapped to the supporting external connections.</p> <p>The network diagram is updated when connections with third parties change or at least annually.</p> <p>Network and systems diagrams are stored in a secure manner with proper restrictions on access.</p> <p>Controls for primary and backup third-party connections are monitored and tested on a regular basis.</p>
',
		'intermediate' 	=> '<p>A validated asset inventory is used to create comprehensive diagrams depicting data repositories, data flow, infrastructure, and connectivity. Security controls are designed and verified to detect and prevent intrusions from third-party connections.</p> <p>Monitoring controls cover all external connections (e.g., third-party service providers, business partners, customers).</p> <p>Monitoring controls cover all internal network-to-network connections.</p>',
		'advanced' 		=> '<p>The security architecture is validated and documented before network connection infrastructure changes.</p> <p>The institution works closely with third-party service providers to maintain and improve the security of external connections.</p>',
		'innovative' 	=> '<p>Diagram(s) of external connections is interactive, shows real-time changes to the network connection infrastructure, new connections, and volume fluctuations, and alerts when risks arise.</p> <p>The institutions connections can be segmented or severed instantaneously to prevent contagion from cyber attacks.</p>',
	];
	$data['domain_4'][advisory_id_from_string('Contracts')] = [
		'baseline' 		=> '<p>Formal contracts that address relevant security and privacy requirements are in place for all third parties that process, store, or transmit confidential data or provide critical services.</p> <p>Contracts acknowledge that the third party is responsible for the security of the institution’s confidential data that it possesses, stores, processes, or transmits.</p> <p>Contracts stipulate that the third-party security controls are regularly reviewed and validated by an independent party.</p> <p>Contracts identify the recourse available to the institution should the third party fail to meet defined security requirements.</p> <p>Contracts establish responsibilities for responding to security incidents.</p> <p>Contracts specify the security requirements for the return or destruction of data upon contract termination.</p>',
		'evolving' 		=> '<p>Responsibilities for managing devices (e.g., firewalls, routers) that secure connections with third parties are formally documented in the contract. Responsibility for notification of direct and indirect security incidents and vulnerabilities is documented in contracts or service-level agreements (SLAs).</p> <p>Contracts stipulate geographic limits on where data can be stored or transmitted.</p>',
		'intermediate' 	=> '<p>Third-party SLAs or similar means are in place that require timely notification of security events.</p>',
		'advanced' 		=> '<p>Contracts require third-party service provider’s security policies meet or exceed those of the institution.</p> <p>A third-party termination/exit strategy has been established and validated with management.</p>
',
		'innovative' 	=> '<p>The institution promotes a sector-wide effort to influence contractual requirements for critical third parties to the industry.</p>',
	];
	$data['domain_4'][advisory_id_from_string('Due Diligence')] = [
		'baseline' 		=> '<p>Risk-based due diligence is performed on prospective third parties before contracts are signed, including reviews of their background, reputation, financial condition, stability, and security controls.</p> <p>A list of third-party service providers is maintained.</p> <p>A risk assessment is conducted to identify criticality of service providers.</p>',
		'evolving' 		=> '<p>A formal process exists to analyze assessments of third-party cybersecurity controls.</p> <p>The board or an appropriate board committee reviews a summary of due diligence results including management’s recommendations to use third parties that will affect the institution’s inherent risk profile.</p>
',
		'intermediate' 	=> '<p>A process is in place to confirm that the institution’s third-party service providers conduct due diligence of their third parties (e.g., subcontractors).</p> <p>Pre-contract, physical site visits of high-risk vendors are conducted by the institution or by a qualified third party.</p>',
		'advanced' 		=> '<p>A continuous process improvement program is in place for third-party due diligence activity.</p> <p>Audits of high-risk vendors are conducted on an annual basis.</p>',
		'innovative' 	=> '<p>The institution promotes sector-wide efforts to build due diligence mechanisms that lead to in-depth and efficient security and resilience reviews.</p> <p>The institution is leading efforts to develop new auditable processes and for conducting due diligence and ongoing monitoring of cybersecurity risks posed by third parties.</p>',
	];
	$data['domain_4'][advisory_id_from_string('Ongoing Monitoring')] = [
		'baseline' 		=> '<p>The third-party risk assessment is updated regularly.</p> <p>Audits, assessments, and operational performance reports are obtained and reviewed regularly validating security controls for critical third parties.</p> <p>Ongoing monitoring practices include reviewing critical third-parties’ resilience plans.</p>',
		'evolving' 		=> '<p>A process to identify new third-party relationships is in place, including identifying new relationships that were established without formal approval. </p> <p>A formal program assigns responsibility for ongoing oversight of thirdparty access.</p> <p>Monitoring of third parties is scaled, in terms of depth and frequency, according to the risk of the third parties. </p> <p>Automated reminders or ticklers are in place to identify when required third-party information needs to be obtained or analyzed.</p>',
		'intermediate' 	=> '<p>Third-party employee access to the institutions confidential data are tracked actively based on the principles of least privilege. </p> <p>Periodic on-site assessments of high-risk vendors are conducted to ensure appropriate security controls are in place.</p>',
		'advanced' 		=> '<p>Third-party employee access to confidential data on third-party hosted systems is tracked actively via automated reports and alerts.</p>',
		'innovative' 	=> '<p>The institution is leading efforts to develop new auditable processes for ongoing monitoring of cybersecurity risks posed by third parties.</p>',
	];
	// DOMAIN 5
	$data['domain_5'][advisory_id_from_string('Detection')] = [
		'baseline' 		=> '<p>Alert parameters are set for detecting information security incidents that prompt mitigating actions.</p> <p>System performance reports contain information that can be used as a risk indicator to detect information security incidents.</p> <p>Tools and processes are in place to detect, alert, and trigger the incident response program.</p>
',
		'evolving' 		=> '<p>The institution has processes to detect and alert the incident response team when potential insider activity manifests that could lead to data theft or destruction.</p>',
		'intermediate' 	=> '<p>The incident response program is triggered when anomalous behaviors and attack patterns or signatures are detected.</p> <p>The institution has the ability to discover infiltration, before the attacker traverses across systems, establishes a foothold, steals information, or causes damage to data and systems.</p> <p>Incidents are detected in real time through automated processes that include instant alerts to appropriate personnel who can respond.</p> <p>Network and system alerts are correlated across business units to better detect and prevent multifaceted attacks (e.g., simultaneous DDoS attack and account takeover).</p> <p>Incident detection processes are capable of correlating events across the enterprise.</p>',
		'advanced' 		=> '<p>Sophisticated and adaptive technologies are deployed that can detect and alert the incident response team of specific tasks when threat indicators across the enterprise indicate potential external and internal threats.</p> <p>Automated tools are implemented to provide specialized security monitoring based on the risk of the assets to detect and alert incident response teams in real time.</p>',
		'innovative' 	=> '<p>The institution is able to detect and block zero-day attempts and inform management and the incident response team in real time.</p>',
	];
	$data['domain_5'][advisory_id_from_string('Escalating And Reporting')] = [
		'baseline' 		=> '<p>A process exists to contact personnel who are responsible for analyzing and responding to an incident.</p> <p>Procedures exist to notify customers, regulators, and law enforcement as required or necessary when the institution becomes aware of an incident involving the unauthorized access to or use of sensitive customer information.</p> <p>The institution prepares an annual report of security incidents or violations for the board or an appropriate board committee.</p> <p>Incidents are classified, logged, and tracked.</p>',
		'evolving' 		=> '<p>Criteria have been established for escalating cyber incidents or vulnerabilities to the board and senior management based on the potential impact and criticality of the risk.</p> <p>Regulators, law enforcement, and service providers, as appropriate, are notified when the institution is aware of any unauthorized access to systems or a cyber incident occurs that could result in degradation of services.</p> <p>Tracked cyber incidents are correlated for trend analysis and reporting.</p>',
		'intermediate' 	=> '<p>Employees that are essential to mitigate the risk (e.g., fraud, business resilience) know their role in incident escalation.</p> <p>A communication plan is used to notify other organizations, including third parties, of incidents that may affect them or their customers.</p> <p>An external communication plan is used for notifying media regarding incidents when applicable.</p>',
		'advanced' 		=> '<p>The institution has established quantitative and qualitative metrics for the cybersecurity incident response process.</p> <p>Detailed metrics, dashboards, and/or scorecards outlining cyber incidents and events are provided to management and are part of the board meeting package.</p> <p>INNOVATIVE</p> <p>A mechanism is in place to provide instantaneous notification of incidents to management and essential employees through multiple communication channels with tracking and verification of receipt.</p>',
		'innovative' 	=> 'amet',
	];
	$data['domain_5'][advisory_id_from_string('Planning')] = [
		'baseline' 		=> '<p>The institution has documented how it will react and respond to cyber incidents.</p>
<p>Communication channels exist to provide employees a means for reporting information security events in a timely manner.</p> <p>Roles and responsibilities for incident response team members are defined.</p> <p>The response team includes individuals with a wide range of backgrounds and expertise, from many different areas within the institution (e.g., management, legal, public relations, as well as information technology).</p> <p>A formal backup and recovery plan exists for all critical business lines.</p> <p>The institution plans to use business continuity, disaster recovery, and data backup programs to recover operations following an incident.</p>',
		'evolving' 		=> '<p>The remediation plan and process outlines the mitigating actions, resources, and time parameters.</p> <p>The corporate disaster recovery, business continuity, and crisis management plans have integrated consideration of cyber incidents.</p> <p>Alternative processes have been established to continue critical activity within a reasonable time period.</p> <p>Business impact analyses have been updated to include cybersecurity.</p> <p>Due diligence has been performed on technical sources, consultants, or forensic service firms that could be called to assist the institution during or following an incident.</p>',
		'intermediate' 	=> '<p>A strategy is in place to coordinate and communicate with internal and external stakeholders during or following a cyber attack.</p> <p>Plans are in place to re-route or substitute critical functions and/or services that may be affected by a successful attack on Internet-facing systems.</p> <p>A direct cooperative or contractual agreement(s) is in place with an incident response organization(s) or provider(s) to assist rapidly with mitigation efforts.</p> <p>Lessons learned from real-life cyber incidents and attacks on the institution and other organizations are used to improve the institution’s risk mitigation capabilities and response plan</p>',
		'advanced' 		=> '<p>Methods for responding to and recovering from cyber incidents are tightly woven throughout the business units’ disaster recovery, business continuity, and crisis management plans.</p> <p>Multiple systems, programs, or processes are implemented into a comprehensive cyber resilience program to sustain, minimize, and recover operations from an array of potentially disruptive and destructive cyber incidents.</p> <p>A process is in place to continuously improve the resilience plan.</p>',
		'innovative' 	=> '<p>The incident response plan is designed to ensure recovery from disruption of services, assurance of data integrity, and recovery of lost or corrupted data following a cybersecurity incident.</p> <p>The incident response process includes detailed actions and rulebased triggers for automated response.</p>',
	];
	$data['domain_5'][advisory_id_from_string('Response And Mitigation')] = [
		'baseline' 		=> '<p>Appropriate steps are taken to contain and control an incident to prevent further unauthorized access to or use of customer information.</p>',
		'evolving' 		=> '<p>The incident response plan is designed to prioritize incidents, enabling a rapid response for significant cybersecurity incidents or vulnerabilities.</p> <p>A process is in place to help contain incidents and restore operations with minimal service disruption.</p> <p>Containment and mitigation strategies are developed for multiple incident types (e.g., DDoS, malware).</p> <p>Procedures include containment strategies and notifying potentially impacted third parties.</p> <p>Processes are in place to trigger the incident response program when an incident occurs at a third party.</p> <p>Records are generated to support incident investigation and mitigation.</p> <p>The institution calls upon third parties, as needed, to provide mitigation services.</p> <p>Analysis of events is used to improve the institutions security measures and policies.</p>',
		'intermediate' 	=> '<p>Analysis of security incidents is performed in the early stages of an intrusion to minimize the impact of the incident.</p> <p>Any changes to systems/applications or to access entitlements necessary for incident management are reviewed by management for formal approval before implementation.</p> <p>Processes are in place to ensure assets affected by a security incident that cannot be returned to operational status are quarantined, removed, disposed of, and/or replaced.</p> <p>Processes are in place to ensure that restored assets are appropriately reconfigured and thoroughly tested before being placed back into operation.</p>',
		'advanced' 		=> '<p>The incident management function collaborates effectively with the cyber threat intelligence function during an incident.</p> <p>Links between threat intelligence, network operations, and incident response allow for proactive response to potential incidents.</p> <p>Technical measures apply defense-in-depth techniques such as deeppacket inspection and black holing for detection and timely response to network-based attacks associated with anomalous ingress or egress traffic patterns and/or DDoS attacks. </p>',
		'innovative' 	=> '<p>The institution’s risk management of significant cyber incidents results in limited to no disruptions to critical services.</p> <p>The technology infrastructure has been engineered to limit the effects of a cyber attack on the production environment from migrating to the backup environment (e.g., air-gapped environment and processes).</p>',
	];
	$data['domain_5'][advisory_id_from_string('Testing')] = [
		'baseline' 		=> '<p>Scenarios are used to improve incident detection and response.</p> <p>Business continuity testing involves collaboration with critical third parties.</p> <p>Systems, applications, and data recovery is tested at least annually.</p>',
		'evolving' 		=> '<p>Recovery scenarios include plans to recover from data destruction and impacts to data integrity, data loss, and system and data availability.</p> <p>Widely reported events are used to evaluate and improve the institutions response.</p> <p>Information backups are tested periodically to verify they are accessible and readable.</p>',
		'intermediate' 	=> '<p>Cyber-attack scenarios are analyzed to determine potential impact to critical business processes.</p> <p>The institution participates in sector-specific cyber exercises or scenarios (e.g., FS-ISAC Cyber Attack (against) Payment Processors (CAPP)).</p> <p>Resilience testing is based on analysis and identification of realistic and highly likely threats as well as new and emerging threats facing the institution.</p> <p>The critical online systems and processes are tested to withstand stresses for extended periods (e.g., DDoS).</p> <p>The results of cyber event exercises are used to improve the incident response plan and automated triggers.</p>',
		'advanced' 		=> '<p>Resilience testing is comprehensive and coordinated across all critical business functions.</p> <p>The institution validates that it is able to recover from cyber events similar to by known sophisticated attacks at other organizations.</p> <p>Incident response testing evaluates the institution from an attackers perspective to determine how the institution or its assets at critical third parties may be targeted.</p> <p>The institution corrects root causes for problems discovered during cybersecurity resilience testing.</p> <p>Cybersecurity incident scenarios involving significant financial loss are used to stress test the institutions risk management.</p>',
		'innovative' 	=> '<p>The institution tests the ability to shift business processes or functions between different processing centers or technology systems for cyber incidents without interruption to business or loss of productivity or data.</p> <p>The institution has validated that it is able to remediate systems damaged by zero-day attacks to maintain current recovery time objectives.</p> <p>The institution is leading the development of more realistic test environments.</p> <p>Cyber incident scenarios are used to stress test potential financial losses across the sector.</p>',
	];
	return empty($data[$domain]) ? false : $data[$domain];
}